id = "blackout-engine"
name = "Blackout Engine"
version = "0.1.1"
schema_version = 1
authors = ["Erik Praznovský <erik@virtualsoaring.eu>"]
description = "Dark theme for Zed editor - Neon/Pastel variants."
repository = "https://github.com/erik-praznovsky/zed-blackout-engine"
